/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface McButton {
        "appearance": string;
        "text": string;
    }
    interface McModal {
        "appearance": string;
        "buttons": string;
        "closeIcon": string;
        "header": string;
        "isopen": boolean;
    }
}
declare global {
    interface HTMLMcButtonElement extends Components.McButton, HTMLStencilElement {
    }
    var HTMLMcButtonElement: {
        prototype: HTMLMcButtonElement;
        new (): HTMLMcButtonElement;
    };
    interface HTMLMcModalElement extends Components.McModal, HTMLStencilElement {
    }
    var HTMLMcModalElement: {
        prototype: HTMLMcModalElement;
        new (): HTMLMcModalElement;
    };
    interface HTMLElementTagNameMap {
        "mc-button": HTMLMcButtonElement;
        "mc-modal": HTMLMcModalElement;
    }
}
declare namespace LocalJSX {
    interface McButton {
        "appearance"?: string;
        "text"?: string;
    }
    interface McModal {
        "appearance"?: string;
        "buttons"?: string;
        "closeIcon"?: string;
        "header"?: string;
        "isopen"?: boolean;
        "onAction"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "mc-button": McButton;
        "mc-modal": McModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mc-button": LocalJSX.McButton & JSXBase.HTMLAttributes<HTMLMcButtonElement>;
            "mc-modal": LocalJSX.McModal & JSXBase.HTMLAttributes<HTMLMcModalElement>;
        }
    }
}
